### PR TITLE
Add support for redisplaying the start screen

### LINKED ISSUE #16: Allow redisplaying start screen
**Is your feature request related to a problem? Please describe.**
Currently, it is impossible to display the start screen again. This limits the versatility of such a system, as it prevents the usage of it as a quick-access dashboard.

**Describe the solution you'd like**
Remove the check in `startup.display()` to allow users to re-display their start screens.

**Describe alternatives you've considered**
If the check is needed to prevent reloading without cause, moving the lock to those places would probably be wise.

### LINKED ISSUE #17: Display title even without folding
**Is your feature request related to a problem? Please describe.**
When working with sections, it is often convenient to use the title option. However, there is no way to do so without folding the section by default.

**Describe the solution you'd like**
Allowing folded sections to be unfolded

**Describe alternatives you've considered**
Titles being handled separately to section folding, though this disallows unfolded-by-default sections.

### PR DESCRIPTION
**Pull request by enderger**
Fixes #16 by running startup in a scratch buffer and removing the startup check, among other fixes to make it work. Now, calling `display` will create a scratch buffer and display the start screen into that.

### CODE REVIEW

**Comment by max397574** [comment]
I've already worked on a fix for this locally and I'm nearly done.
This pull request would also break some stuff

**Comment by pejax** [comment]
I am using the latest version and tried to re-display startify with this command
:lua require('startup').display(true)
startup
and get duplicated content upon reload.
startup-1
Do I use the command correctly?

**Comment by max397574** [comment]
does it happen with `:Startup display` as well?

**Comment by enderger** [comment]
This PR wasn’t merged, but I do recall that part of it fixes this bug (encountered it then). Haven’t had much time to work on my Vim config, so I haven’t had the chance to check if it works in the merged version.

**Comment by max397574** [comment]
@pejax this should be fixed now

**Comment by pejax** [comment]
@max397574 Thanks for the quick merge -  `:Startup display` works as expected now.

**Pull request closed without merging**
